### ISSUE TITLE
Array Inder Error

### ISSUE THREAD

**Issue by ragulm17** [blopker/KDD-Music-Recommender#1]
Usage:
Array Index error
java -jar KDD-Music-Recommender.jar -k N DATABASE
java -jar KDD-Music-Recommender.jar -q -t D -n NEIGHBOR_FILE DATABASE
 -k N   : How many nearest neighbors to calculate.
 -n VAL : Neighborhood file, used for query only
 -q     : Activate query mode!!!
 -t N   : Threshold, used for query only
C:\Users\Raga\AppData\Local\NetBeans\Cache\8.1\executor-snippets\run.xml:53: Java returned: 1
BUILD FAILED (total time: 0 seconds)
This is the error that i am facing once i run the program.
Any suggestion?

**Comment by blopker** [comment]
Hey @ragulm17, this is a very old class project and I have no idea how to run it any more. Feel free to do anything you'd like with it, but I can't help you much. Sorry!
